//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.16 at 07:30:39 PM CST 
//


package com.itxxr.easyorm.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="databaseFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entityFieldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entityFieldType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldConfig")
public class FieldConfig {

    @XmlAttribute(name = "databaseFieldName")
    protected String databaseFieldName;
    @XmlAttribute(name = "entityFieldName")
    protected String entityFieldName;
    @XmlAttribute(name = "entityFieldType")
    protected String entityFieldType;

    /**
     * Gets the value of the databaseFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseFieldName() {
        return databaseFieldName;
    }

    /**
     * Sets the value of the databaseFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseFieldName(String value) {
        this.databaseFieldName = value;
    }

    /**
     * Gets the value of the entityFieldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityFieldName() {
        return entityFieldName;
    }

    /**
     * Sets the value of the entityFieldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityFieldName(String value) {
        this.entityFieldName = value;
    }

    /**
     * Gets the value of the entityFieldType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityFieldType() {
        return entityFieldType;
    }

    /**
     * Sets the value of the entityFieldType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityFieldType(String value) {
        this.entityFieldType = value;
    }

}
